### PR TITLE
add verkiezingen zonder strijd results

### PR DESCRIPTION
**Pull request by Rahien**
## Description

adds the results for Lo-Reninge and Herstappe where there were 'verkiezingen zonder strijd'

### CODE REVIEW

**Review by bfidlers — COMMENTED** [review]
It looks good and I can prepare the legislature for both municipalities. However, I can't seem to access the verkiezingsuitslag page for Lo-Reninge, not sure if this is a bigger problem or something wrong with the migration.

Screenshot 2024-11-05 at 12 09 41

**Comment by Rahien** [comment]
> It looks good and I can prepare the legislature for both municipalities. However, I can't seem to access the verkiezingsuitslag page for Lo-Reninge, not sure if this is a bigger problem or something wrong with the migration.
> 
Could it be that you ran the migrations after this was cached and you didn't restart resource & cache?

**Comment by bfidlers** [comment]
> > It looks good and I can prepare the legislature for both municipalities. However, I can't seem to access the verkiezingsuitslag page for Lo-Reninge, not sure if this is a bigger problem or something wrong with the migration.
> 
> Could it be that you ran the migrations after this was cached and you didn't restart resource & cache?

Yes I only restarted migrations, will try rerunning them.

**Comment by bfidlers** [comment]
Seems like it was indeed a caching issue.

**Review by bfidlers — APPROVED** [review]

**Pull request merged**
